### ISSUE TITLE
[Crash Report] crash after adding a same track 2 times in a same playlist

### ISSUE THREAD

**Issue by pixel2user** [chr56/Phonograph_Plus#169]
### Crash log

```
Crash Report:
Package name:    player.phonograph.plus
App version:     1.5.2 (1052)
Git Commit Hash: d6f721af75b773b3c85f28703666cade18a3d5bb
Android version: 12 (SDK 32)
Device brand:    google  (by Google)
Language:        de

Stacktrace:
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:w{86310d7 position=11 id=1000024795, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:w{454bd06 position=10 id=1000024795, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{f64b683 VFED..... ......ID 0,0-1380,2542 #7f09025d app:id/recycler_view}, adapter:nf.a0@8f7d201, layout:androidx.recyclerview.widget.LinearLayoutManager@e99ddc4, context:player.phonograph.ui.modules.playlist.PlaylistDetailActivity@a08e8fc
	at androidx.recyclerview.widget.RecyclerView.v(SourceFile:339)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(SourceFile:392)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SourceFile:142)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3755)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Version

1.5.2

### Steps to reproduce the bug

Steps to reproduce:
1. Create a new m3u playlist
2. Add a new track to the playlist
3. Add the same track again
4. Go to the playlist track view
5. Tab and hold the track name to trigger "java.lang.IllegalStateException: Two different ViewHolders have the same stable ID."

**Comment by pixel2user** [comment]
Same crash with new app version 1.6.0 (1060)

**Comment by pixel2user** [comment]
"Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change."

**Comment by pixel2user** [comment]
@chr56 As a quick fix it would be OK to don't a the track a second time.

**Comment by chr56** [comment]
I do not know, but actually I can not reproduce this bug, however, it _of course exists_ (As you can see in the relative codes, the id of `ViewHolder` uses its song id, which make it able to duplicate, just like a previous bug of Playing Queue Adapter.)

Yet, I am kind of busy on something else, though this should be easy to fix.

**Comment by chr56** [comment]
I could not reproduce somehow, so I have to shot in blind (bc746441):


Try this:
[PhonographPlus-Preview-144b0408.zip](https://github.com/chr56/Phonograph_Plus/files/15009782/PhonographPlus-Preview-144b0408.zip)

**Comment by pixel2user** [comment]
The app no longer crashes when I press and hold one of the title entries.

**Comment by pixel2user** [comment]
But: There is no function to remove an entry of the playlist. This is not specific to the redundant track but is the case with all tracks.

**Comment by chr56** [comment]
> But: There is no function to remove an entry of the playlist. 

Yeah, the playlist editing is problematical since long ago, I do not have energy to rework of that.

**Comment by chr56** [comment]
Fixed.

> But: There is no function to remove an entry of the playlist. This is not specific to the redundant track but is the case with all tracks.


[PhonographPlus-Preview-3994fa1f.zip](https://github.com/chr56/Phonograph_Plus/files/15012780/PhonographPlus-Preview-3994fa1f.zip)

**Comment by pixel2user** [comment]
> Fixed.
> > But: There is no function to remove an entry of the playlist. This is not specific to the redundant track but is the case with all tracks.
> 
> [PhonographPlus-Preview-3994fa1f.zip](https://github.com/chr56/Phonograph_Plus/files/15012780/PhonographPlus-Preview-3994fa1f.zip)

I don't see any difference to the other preview version!?

The action menu for the track is still missing a 'Remove from playlist' action in the playlist view. And 'Remove from playing queue' is shown instead as is shown in the playing queue view.

**Comment by pixel2user** [comment]
I opened a new bug ticket for the missing action: #171

**Comment by pixel2user** [comment]
`Remove from playlist` doesn't remove the track from my playlist.

But don't worry. This is not important for me and I will simply recreate the playlist.

**Comment by chr56** [comment]
> `Remove from playlist` doesn't remove the track from my playlist.

After Android 11, you may need to grant `Manage All Files`/`Allow management of all files` permission (I forget to add checks and tips) to make it actually work (Sorry, this action does not support SAF _for now_). 


(Shortcut: `Main drawer` -> `More` -> `Grant External Storage Permission`)
