### ISSUE TITLE
[Bug] Wrong covers when scrolling

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#181]
### Bug Summary

If you scroll up the content of a tab while it is still loading, the covers are assigned and display to wrong artist / album whatever.

### Version

1.6.2

### Steps to reproduce the bug

1. Have a huge music collection
2. Start phonograph
3. Select artists tab
4. Scroll the content up while it is still loading
5. Cover assignment to artist is completely wrong (cover from some rows above then the actual)

The incorrect assignment is even retained when you go into the details and back again. If you do not scroll the correct covers are displayed.

Looks like a timing problem during loading, probably a race condition.

### Environment

AOSP 13

### Screenshots or Screen recordings

![Bildschirmfoto vom 2024-05-08 18-43-28](https://github.com/chr56/Phonograph_Plus/assets/418685/bb60fa68-1007-4339-a111-7f3560258560)

**Comment by chr56** [comment]
Confirmed since version `v1.4.4 (2024.01.30)`

**Comment by chr56** [comment]
Fixed in [v1.7.1-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7.1-dev2).

**Comment by chr56** [comment]
[v1.7.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.1) has released, closed!

**Comment by eku** [comment]
I can still reproduce the bug with 1.7.1. Look at "Coolio", "Cosmix feat Ernie", and "CCR".

![Screenshot_20240613-174854_Trebuchet](https://github.com/chr56/Phonograph_Plus/assets/418685/b77d55c4-3137-41cc-be6f-0248e45a246d)
![Screenshot_20240613-174903_Trebuchet](https://github.com/chr56/Phonograph_Plus/assets/418685/18b22170-9dcc-41c4-8a3e-4f3395fd3117)

**Comment by russianspy1234** [comment]
Have this bug on 1.7.1 as well

**Comment by russianspy1234** [comment]
I turned off preload images and image cache and that seems to have solved it

**Comment by eku** [comment]
The setting `Image Cache` was and still is disabled. So that could not be the root cause.

**Comment by sigzegv** [comment]
Same issue here in 1.8, also disabling Preload images fixes the as a workaround.

**Comment by eku** [comment]
> Now this bug should be utimately fixed in [preview_1.9.3-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.9.3-dev2) and later, along with performance improvement of loading; thus, _preload images_ could be disabled now.

Which commits are related to this?
