### ISSUE TITLE
[Bug Report] Phonograph Plus crashed when resizing in Freeform Mode

### ISSUE THREAD

**Issue by hmtheboy154** [chr56/Phonograph_Plus#31]
**Describe the bug or unexpected behavior**
When open the app with freeform mode and try to resize the app, it will crash

**Crash log**
```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.3 (311)
Git Commit Hash: fec22849337fddb81837
Android version: 11 (SDK 30)
Device brand:    Android-x86  (by unknown)
Device model:    Generic Android-x86_64 (code: x86_64)
Product name:    bliss_x86_64
Build version:   RSV1.210329.052 
                 (eng.hmtheb.20220924.071710)
Hardware:        bliss_x86_64
Language:        vi

java.lang.NullPointerException
 at player.phonograph.ui.fragments.player.card.CardPlayerFragment.access$getViewBinding(Unknown Source:2)
 at player.phonograph.ui.fragments.player.card.CardPlayerFragment$b.c(Unknown Source:7)
 at player.phonograph.ui.fragments.player.card.CardPlayerFragment.onColorChanged(SourceFile:1)
 at player.phonograph.ui.fragments.player.h.invokeSuspend(Unknown Source:13)
 at q3.a.resumeWith(Unknown Source:8)
 at h4.m0.run(Unknown Source:86)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7669)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Suppressed: h4.k0: [w1{Cancelling}@17e95d9, Dispatchers.Main]
```

**How to reproduce**
- Open recents, press the app logo on and choose `Freeform`. If there is no freeform, open Developer Settings and turn on `Enable Freeform windows`
- Try to resize, it will crash

**Comment by hmtheboy154** [comment]
bug report on my phone

```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.3 (311)
Git Commit Hash: fec22849337fddb81837
Android version: 11 (SDK 30)
Device brand:    OnePlus  (by OnePlus)
Device model:    AC2003 (code: Nord)
Product name:    Nord
Build version:   RQ3A.211001.001 
                 (eng.jenkin.20220215.132445)
Hardware:        qcom
Language:        vi

java.lang.IllegalStateException: Fragment PlayerAlbumCoverFragment{5f6fa65} (a14b2178-ae60-46ef-b0c8-7ada3515db4c) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(SourceFile:2)
	at androidx.viewpager2.adapter.FragmentStateAdapter.<init>(Unknown Source:0)
	at h7.a.<init>(Unknown Source:10)
	at player.phonograph.ui.fragments.player.PlayerAlbumCoverFragment.N(SourceFile:3)
	at r8.e.handleMessage(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


```

**Comment by chr56** [comment]
Confirmed

**Comment by chr56** [comment]
_**partially**_ fixed in [v0.3.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.4)

**Comment by hmtheboy154** [comment]
> _**partially**_ fixed in [v0.3.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.4)

still crashing

**Comment by chr56** [comment]
> still crashing
That is why it called "partially".

Look that to fix it once for all requires completely rework the player.
I am trying to fix it temperately, but if not successful, you might have to wait until I rework the whole player.

_Be patient!_

**Comment by chr56** [comment]
[Preview-06758fe6.zip](https://github.com/chr56/Phonograph_Plus/files/9732826/Preview-06758fe6.zip)

Try this, it's fine for me, however, **it still might crash**, but in **rare** conditions or  if resizing **too quickly**.
So, be gentle to it.

**Comment by chr56** [comment]
Close, it should be fixed in [v0.3.5.1-LTS](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.5.1-LTS)

**Comment by hmtheboy154** [comment]
> [Preview-06758fe6.zip](https://github.com/chr56/Phonograph_Plus/files/9732826/Preview-06758fe6.zip)
> 
> Try this, it's fine for me, however, **it still might crash**, but in **rare** conditions or if resizing **too quickly**. So, be gentle to it.

Yes it's still crash if I go too fast
But anyway this is fine, thanks for fixing it.

**Comment by chr56** [comment]
Completely fix this bug need more time, and in [v0.3.5.1-LTS](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.5.1-LTS), you should wait util **all stuffs and things are loaded** ,then you can resize it again.
