### ISSUE TITLE
[Bug]: Failure to display any cover

### ISSUE THREAD

**Issue by Porkepix** [chr56/Phonograph_Plus#65]
### Bug Summary

After using Phonograph years ago, and then satisfied with Vinyl, I was curious to give a look at Phonograph plus, see what was different considering the common roots for both (also, that's out of topic, but I'm guessing that to fork it rather than go on Vinyl you had your mind set onto different directions?)

Now for the issue itself, I unfortunately could see that Phonograph plus was failing to load any covers at all, which wasn't the case for any other media player I tried before, including the old Phonograph, so I'd exclude problems in the files themselves.

### Version

0.6.0

### Steps to reproduce the bug

Just run phonograph plus

### Environment

Phone running stock Android Oreo (8.0).

### Other helpful information

Here are some crash logs I could gather from `adb logcat -v threadtime`.

There are a lot, and maybe not everything is related to covers loading.

<details>
<summary>`adb logcat -v threadtime` logs</summary>

```
03-11 12:11:13.844 30288 30288 W View    : requestLayout() improperly called by androidx.swiperefreshlayout.widget.SwipeRefreshLayout{d80c75a V.ED..... ......ID 0,0-1080,1560 #7f0900ce app:id/container} during layout: running second layout pass
03-11 12:11:13.844 30288 30288 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{8f82631 V.ED..... ..S..AID 39,43-177,100} during layout: running second layout pass
03-11 12:11:13.844 30288 30288 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{8316116 V.ED..... ......ID 36,43-213,100} during layout: running second layout pass
03-11 12:11:13.922 30288 30317 W System.err: java.io.IOException: Stream Closed
03-11 12:11:13.922 30288 30317 W System.err: 	at java.io.FileInputStream.read(FileInputStream.java:251)
03-11 12:11:13.922 30288 30317 W System.err: 	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:940)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.r.q(Unknown Source:45)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.c0.q(Unknown Source:36)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.n.q(Unknown Source:7)
03-11 12:11:13.922 30288 30317 W System.err: 	at l3.b$a.q(Unknown Source:0)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.c0.l(Unknown Source:32)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.a0.q(Unknown Source:55)
03-11 12:11:13.922 30288 30317 W System.err: 	at p8.c0$a.read(Unknown Source:36)
03-11 12:11:13.922 30288 30317 W System.err: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
03-11 12:11:13.922 30288 30317 W System.err: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:742)
03-11 12:11:13.922 30288 30317 W System.err: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:718)
03-11 12:11:13.922 30288 30317 W System.err: 	at l3.b.b(SourceFile:5)
03-11 12:11:13.922 30288 30317 W System.err: 	at l3.b$d.invoke(Unknown Source:7)
03-11 12:11:13.922 30288 30317 W System.err: 	at c7.f1.invokeSuspend(SourceFile:26)
03-11 12:11:13.923 30288 30317 W System.err: 	at c7.f1.invoke(SourceFile:13)
03-11 12:11:13.923 30288 30317 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:13.923 30288 30317 W System.err: 	at c7.i0.m(SourceFile:19)
03-11 12:11:13.923 30288 30317 W System.err: 	at c7.g1.a(SourceFile:9)
03-11 12:11:13.923 30288 30317 W System.err: 	at l3.b.a(Unknown Source:97)
03-11 12:11:13.923 30288 30317 W System.err: 	at p3.a.b(Unknown Source:132)
03-11 12:11:13.923 30288 30317 W System.err: 	at p3.d.invokeSuspend(Unknown Source:54)
03-11 12:11:13.923 30288 30317 W System.err: 	at p3.d.invoke(SourceFile:13)
03-11 12:11:13.923 30288 30317 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:13.923 30288 30317 W System.err: 	at c7.i0.m(SourceFile:50)
03-11 12:11:13.923 30288 30317 W System.err: 	at p3.a.c(SourceFile:347)
03-11 12:11:13.923 30288 30317 W System.err: 	at p3.f.invokeSuspend(SourceFile:38)
03-11 12:11:13.923 30288 30317 W System.err: 	at l6.a.resumeWith(Unknown Source:8)
03-11 12:11:13.923 30288 30317 W System.err: 	at c7.q0.run(Unknown Source:102)
03-11 12:11:13.923 30288 30317 W System.err: 	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
03-11 12:11:13.923 30288 30317 W System.err: 	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
03-11 12:11:13.923 30288 30317 W System.err: 	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
03-11 12:11:13.929 30288 30317 D skia    : ---- read threw an exception
03-11 12:11:13.938 30288 30311 I vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
03-11 12:11:13.938 30288 30317 D skia    : --- SkAndroidCodec::NewFromStream returned null
03-11 12:11:13.962 30288 30288 V ReflectMenu: No field mOverflowPopup in class Landroidx/appcompat/view/menu/b; (declaration of 'androidx.appcompat.view.menu.b' appears in base.apk)
03-11 12:11:13.969  1398  1454 I ActivityManager: Displayed player.phonograph.plus/player.phonograph.ui.activities.MainActivity: +1s12ms (total +1s268ms)
03-11 12:11:13.979 30288 30288 V ReflectMenu: No field mOverflowPopup in class Landroidx/appcompat/view/menu/b; (declaration of 'androidx.appcompat.view.menu.b' appears in base.apk)
```

```
03-11 12:11:14.279 30288 30339 W System.err: java.io.IOException: Stream Closed
03-11 12:11:14.279 30288 30339 W System.err: 	at java.io.FileInputStream.read(FileInputStream.java:251)
03-11 12:11:14.279 30288 30339 W System.err: 	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:940)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.r.q(Unknown Source:45)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.c0.q(Unknown Source:36)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.n.q(Unknown Source:7)
03-11 12:11:14.279 30288 30339 W System.err: 	at l3.b$a.q(Unknown Source:0)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.c0.l(Unknown Source:32)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.a0.q(Unknown Source:55)
03-11 12:11:14.279 30288 30339 W System.err: 	at p8.c0$a.read(Unknown Source:36)
03-11 12:11:14.279 30288 30339 W System.err: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
03-11 12:11:14.279 30288 30339 W System.err: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:742)
03-11 12:11:14.279 30288 30339 W System.err: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:718)
03-11 12:11:14.279 30288 30339 W System.err: 	at l3.b.b(SourceFile:5)
03-11 12:11:14.279 30288 30339 W System.err: 	at l3.b$d.invoke(Unknown Source:7)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.f1.invokeSuspend(SourceFile:26)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.f1.invoke(SourceFile:13)
03-11 12:11:14.279 30288 30339 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.i0.m(SourceFile:19)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.g1.a(SourceFile:9)
03-11 12:11:14.279 30288 30339 W System.err: 	at l3.b.a(Unknown Source:97)
03-11 12:11:14.279 30288 30339 W System.err: 	at p3.a.b(Unknown Source:132)
03-11 12:11:14.279 30288 30339 W System.err: 	at p3.d.invokeSuspend(Unknown Source:54)
03-11 12:11:14.279 30288 30339 W System.err: 	at p3.d.invoke(SourceFile:13)
03-11 12:11:14.279 30288 30339 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.i0.m(SourceFile:50)
03-11 12:11:14.279 30288 30339 W System.err: 	at p3.a.c(SourceFile:347)
03-11 12:11:14.279 30288 30339 W System.err: 	at p3.f.invokeSuspend(SourceFile:38)
03-11 12:11:14.279 30288 30339 W System.err: 	at l6.a.resumeWith(Unknown Source:8)
03-11 12:11:14.279 30288 30339 W System.err: 	at c7.q0.run(Unknown Source:102)
03-11 12:11:14.280 30288 30339 W System.err: 	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
03-11 12:11:14.280 30288 30339 W System.err: 	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
03-11 12:11:14.280 30288 30339 W System.err: 	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
03-11 12:11:14.280 30288 30339 D skia    : ---- read threw an exception
03-11 12:11:14.280 30288 30339 D skia    : --- SkAndroidCodec::NewFromStream returned null
03-11 12:11:14.313  1027 19528 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.313  1027 19528 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.313  1027 19528 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.313  1027 19528 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.315  1027  2010 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.315  1027  2010 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.315  1027  2010 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.315  1027  2010 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.316  1027 19514 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.316  1027 19514 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.316  1027 19514 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.316  1027 19514 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.318  1027 19489 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.318  1027 19489 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.318  1027 19489 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.318  1027 19489 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.328  1029 19502 E MediaExtractor: Trace connect 0xf13f61a0 0xf13add80
03-11 12:11:14.329  1029 19526 E MediaExtractor: Trace connect 0xefabd720 0xefae82c0
03-11 12:11:14.333  1029 19526 E MetadataRetrieverClient: failed to extract an album art
03-11 12:11:14.333  1029  1318 E MediaExtractor: Trace connect 0xee703920 0xefae8b00
03-11 12:11:14.333  1027  1027 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.333  1027  1027 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.333  1027  1027 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.333  1027  1027 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.334  1029 19504 E MediaExtractor: Trace connect 0xf13f6160 0xefae8dc0
03-11 12:11:14.334  1029 19502 E MetadataRetrieverClient: failed to extract an album art
03-11 12:11:14.334 30288 30323 E MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed.
03-11 12:11:14.339  1029  4096 I ExtendedUtils: printFileName fd(24) -> /storage/8694-1D07/Music/03 - Sonatine.mp3
03-11 12:11:14.339  1029  1318 E MetadataRetrieverClient: failed to extract an album art
03-11 12:11:14.340  1027 19532 I ExtendedExtractor: QTIParser is prefered .. flags 0
03-11 12:11:14.340  1027 19532 I QComExtractorFactory: QTI parser is not preferred for mime: audio/mpeg
03-11 12:11:14.340  1027 19532 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
03-11 12:11:14.340  1027 19532 I ExtendedExtractor: ExtendedExtractor::create 0x0
03-11 12:11:14.341  1029 19504 E MetadataRetrieverClient: failed to extract an album art
03-11 12:11:14.341 30288 30339 W System.err: java.io.IOException: Stream Closed
03-11 12:11:14.341 30288 30339 W System.err: 	at java.io.FileInputStream.read(FileInputStream.java:251)
03-11 12:11:14.342 30288 30339 W System.err: 	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:940)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.r.q(Unknown Source:45)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.c0.q(Unknown Source:36)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.n.q(Unknown Source:7)
03-11 12:11:14.342 30288 30339 W System.err: 	at l3.b$a.q(Unknown Source:0)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.c0.l(Unknown Source:32)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.a0.q(Unknown Source:55)
03-11 12:11:14.342 30288 30339 W System.err: 	at p8.c0$a.read(Unknown Source:36)
03-11 12:11:14.342 30288 30339 W System.err: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
03-11 12:11:14.342 30288 30339 W System.err: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:742)
03-11 12:11:14.342 30288 30339 W System.err: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:718)
03-11 12:11:14.342 30288 30339 W System.err: 	at l3.b.b(SourceFile:5)
03-11 12:11:14.342 30288 30339 W System.err: 	at l3.b$d.invoke(Unknown Source:7)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.f1.invokeSuspend(SourceFile:26)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.f1.invoke(SourceFile:13)
03-11 12:11:14.342 30288 30339 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.i0.m(SourceFile:19)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.g1.a(SourceFile:9)
03-11 12:11:14.342 30288 30339 W System.err: 	at l3.b.a(Unknown Source:97)
03-11 12:11:14.342 30288 30339 W System.err: 	at p3.a.b(Unknown Source:132)
03-11 12:11:14.342 30288 30339 W System.err: 	at p3.d.invokeSuspend(Unknown Source:54)
03-11 12:11:14.342 30288 30339 W System.err: 	at p3.d.invoke(SourceFile:13)
03-11 12:11:14.342 30288 30339 W System.err: 	at a3.a.g0(SourceFile:5)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.i0.m(SourceFile:50)
03-11 12:11:14.342 30288 30339 W System.err: 	at p3.a.c(SourceFile:347)
03-11 12:11:14.342 30288 30339 W System.err: 	at p3.f.invokeSuspend(SourceFile:38)
03-11 12:11:14.342 30288 30339 W System.err: 	at l6.a.resumeWith(Unknown Source:8)
03-11 12:11:14.342 30288 30339 W System.err: 	at c7.q0.run(Unknown Source:102)
03-11 12:11:14.342 30288 30339 W System.err: 	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
03-11 12:11:14.342 30288 30339 W System.err: 	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
03-11 12:11:14.342 30288 30339 W System.err: 	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
03-11 12:11:14.342 30288 30339 D skia    : ---- read threw an exception
03-11 12:11:14.342 30288 30339 D skia    : --- SkAndroidCodec::NewFromStream returned null
```

</details>

Exceptions continues after that but seems to repeat always the same one.

**Comment by chr56** [comment]
Try to go to `Image Source Config`, and modify some of them.

This is an existing bug. #52

**Comment by Porkepix** [comment]
> Try to go to `Image Source Config`, and modify some of them.
> 
> This is an existing bug. #52

What do you mean by "modify", because currently, all 4 of them are checked.

**Comment by chr56** [comment]
> > Try to go to `Image Source Config`, and modify some of them.
> > This is an existing bug. #52
> 
> What do you mean by "modify", because currently, all 4 of them are checked.

JUST DO SOME MODIFICATION (check/uncheck/swap/reorder).

For example, leave just one item checked for each item.

So we can make sure which one(s) might be failing.

Tips: Images are retrieved in the order from top to bottom.

**Comment by chr56** [comment]
BTW, please restart application to apply changes on image source configuration; sorry I forgot.

**Comment by Porkepix** [comment]
So, the source of the exceptions seems to be the first entry, `Android MediaStore`.
But if the second entry (`Android Media Metadata Retriever`) is checked while the first is uncheck, it doesn't work either and Phonograph Plus suffer from very high performance issues. Regular freezes, scrolling isn't smooth and so on, but nothing related seems to appear in the `logcat`. Covers/arts doesn't load either if that second entry is checked.
The only way for Art/Covers to load is to uncheck both of those: if any one of those two is checked, this is broken and no cover/art is loaded.

**Comment by chr56** [comment]
I see, this is a bug that I _only_ reproduced on lower version Android devices(Android N).

It's not easy to fix this, and it takes time. Please be patient, thank you.

**Comment by dremus-alt** [comment]
Hello everybody,
i get this bug on my Samsung S5 (SM-G901F) with Divest OS 16.0 (Android 9) and fixed it Mike Porkepix describes.
Thank you.

**Comment by presjpolk** [comment]
I'm on Android 14 on a Pixel 7 Pro and only about half my album art is loading. I've tried messing with the settings, reordering, rebooting the app, nothing gets me there.

**Comment by chr56** [comment]
[PhonographPlus_image_fix.zip](https://github.com/chr56/Phonograph_Plus/files/13848791/PhonographPlus_image_fix.zip)

The problem should be fixed in this Preview above (at least fixed on my old Android N device).

**Comment by chr56** [comment]
[v1.4.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.3) has been released! This (referred in logs) should be fixed! Close!

**Comment by mennojansz** [comment]
FYI this bug is still happening. I'm on Android 15 and Phonograph Plus 1.11.0 Modern 

Only by rearranging and unchecking options as described above resolved the issue for me
